import Head from 'next/head'
import Image from 'next/image'
import AdvanceBooking from '../components/AdvanceBooking/advanceBooking'
import Carousle from '../components/Carousle/carousle'
import DownloadApp from '../components/DownloadApp/downloadApp'
import FoodGrid from '../components/FoodList/foodGrid'
import OurServices from '../components/OurServices/ourServices'
import RestaurantList from '../components/restaurantList/restaurantList'
import styles from '../styles/Home.module.css'
import {Paper, InputBase, Button, IconButton} from '@mui/material'
import PinDropIcon from '@mui/icons-material/PinDrop';
import { style } from '@mui/system'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>eatiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.sliderBlock} >
          <div style={{display:'flex', flex: 1, justifyContent:'center', flexDirection: 'column'}}>
            <span className={styles.food}>FOOD</span>
            <h1 style={{color: 'purple'}}>Discover Restaurent<br/>& Delicious Food</h1>
            <Paper
                elevation={1}
                    component="form"
                    sx={{  margin: '1.5em 0', display: 'flex', alignItems: 'center' }}
                    className={styles.inp}
                >

                    <InputBase
                        sx={{ ml: 1, flex: 1 }}
                        placeholder="search restaurant,food"
                        inputProps={{ 'aria-label': 'search restaurant,food' }}
                    />

                        <Button className={styles.goSearchButton}  variant="contained">GO</Button>
                    
                </Paper>
                <div className={styles.location}><PinDropIcon/>Hydrabad</div>
          </div>
          <Carousle />
        </div>

        <div className={styles.block}>
          <div className={styles.section1}>
            <span >some top restaurant for  dining <br />out or in!</span>
          </div>
          <div className={styles.section2}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </div>
        </div>

        <RestaurantList />

        <AdvanceBooking />

        <div className={styles.block}>
          <div className={styles.section1}>
            <span >Our <br />Services</span>
          </div>
          <div className={styles.section2}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </div>
        </div>

        <OurServices />

        <FoodGrid />

        <DownloadApp />

      </main>


    </div>
  )
}
